name: WAF Control

on:
  push:
    branches: [ main ]
    paths:
      - 'config/'
      - 'scripts/'
      - '.github/workflows/'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # runs daily at midnight UTC

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pydantic requests PyYAML tenacity

    - name: Apply WAF settings
      run: python scripts/apply_cloudflare.py --config config/cloudflare.yaml
